apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipe-start
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: pipeline-config
    repoURL: 'git@github.com:/raycon300/gitops-pipelines-config'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated: null
