{{ if .Values.pipelines }}
{{ range $pipeline := .Values.pipelines }}
---
apiVersion: v1
data:
  .git-credentials: aHR0cDovL2dvZ3MtYWRtaW46YWRtaW5AZ2l0LWdvZ3MtdW5zYWZlLWdvZ3MuYXBwcy1jcmMudGVzdGluZw==
  .gitconfig: W2NyZWRlbnRpYWwgImh0dHA6Ly9naXQtZ29ncy11bnNhZmUtZ29ncy5hcHBzLWNyYy50ZXN0aW5nLyJdCiAgaGVscGVyID0gc3RvcmU=
kind: Secret
metadata:
  name: git-auth-{{ $pipeline.pipeName }}
  namespace: {{ $pipeline.projectOcName }}
type: Opaque
{{ end }}
{{ end }}
