{{ if .Values.pipelines }}
{{ range $pipeline := .Values.pipelines }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-build-workspace-{{ $pipeline.pipeName }}
  namespace: {{ $pipeline.projectOcName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
{{ end }}
{{ end }}
