{{ if .Values.pipelines }}
{{ range $pipeline := .Values.pipelines }}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git  
  name: git-update-deployment
  namespace: {{ $pipeline.namespace }}
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: community
spec:
  description: This Task can be used to update image digest in a Git repo using kustomize
  params:
    - name: GIT_REPOSITORY
      type: string
    - name: CURRENT_IMAGE
      type: string
    - name: NEW_IMAGE
      type: string
    - name: NEW_DIGEST
      type: string
    - name: APP_MANIFESTS_PATH
      type: string
    - name: GIT_HASH_COMMIT
      type: string
    - name: APP_BRANCH          
      type: string
    - name: SOURCE_BRANCH     
      type: string
  results:
    - description: The commit SHA
      name: commit
  steps:      
    - image: 'docker.io/alpine/git:v2.26.2'
      name: git-clone
      resources: {}
      script: |
        cp /workspace/basic-auth/.git-credentials ~/.git-credentials
        cp /workspace/basic-auth/.gitconfig ~/.gitconfig
        rm -fr git-update-tag-workdir
        git -c http.sslVerify=false clone -b $(params.SOURCE_BRANCH) $(params.GIT_REPOSITORY) git-update-tag-workdir
        
      workingDir: $(workspaces.workspace.path)
    - image: alpine    
      name: update-digest
      resources: {}
      script: |   
        cp /workspace/basic-auth/.git-credentials ~/.git-credentials
        cp /workspace/basic-auth/.gitconfig ~/.gitconfig
        cd git-update-tag-workdir 
        cd $(params.APP_MANIFESTS_PATH)

        DEPLOY_FILE=$(grep "config-file" * |awk -F":" '{print $1}')
        LAST_IMAGE=$(grep "nameVersion:" $DEPLOY_FILE |awk -F":" '{print $4}')
        LI=$(echo -n $LAST_IMAGE)

        sed -i "s/$LI/$(params.GIT_HASH_COMMIT)/g" $DEPLOY_FILE

      workingDir: $(workspaces.workspace.path)
    - image: 'docker.io/alpine/git:v2.26.2'
      name: git-commit
      resources: {}
      script: |
        cp /workspace/basic-auth/.git-credentials ~/.git-credentials
        cp /workspace/basic-auth/.gitconfig ~/.gitconfig

        cd git-update-tag-workdir

        git config user.email "pipelines-ci@redhat.com"
        # git config user.name "$GIT_USER"

        # echo "Showing status git repo"
        git status

        echo "Executing git add"
        git add .      

        echo "Executing git commit "        
        git commit -m "[$(context.taskRun.name)] Image tag updated"             

        echo "Add remote"    
       
        REPOSITORY=$(echo $(params.GIT_REPOSITORY) | sed -E "s#https://(.*)#https://$GIT_USER:$GIT_TOKEN@\1#g")  

        git remote add auth-origin $REPOSITORY
        
        # echo "Executing git push"
        git -c http.sslVerify=false push auth-origin $(params.SOURCE_BRANCH)
      workingDir: $(workspaces.workspace.path)
      
  workspaces:
    - description: The workspace consisting of maven project.
      name: workspace 
    - description: Git auth
      name: basic-auth
{{ end }}
{{ end }}
