{{ if .Values.pipelines }}
{{ $nexus := $.Values.nexus  }}
{{ range $pipeline := .Values.pipelines }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings-{{ $pipeline.pipelineName }}
  namespace: {{ $pipeline.namespace }}
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
      <servers>
        <server>
          <id>nexus</id>
          <username>{{  $nexus.config.user }}</username>
          <password>{{  $nexus.config.pass }}</password>
        </server>
        <server>
            <id>nexus-snapshot</id>
            <username>{{  $nexus.config.user }}</username>
            <password>{{  $nexus.config.pass }}</password>
        </server>
        <server>
            <id>nexus-releases</id>
            <username>{{  $nexus.config.user }}</username>
            <password>{{  $nexus.config.pass }}</password>
        </server>        
      </servers>
      <profiles>
          <profile>
            <id>nexus</id>
            <repositories>
                <repository>
                  <id>public</id>
                  <url>{{  $nexus.config.url }}/repository/maven-public/</url>
                </repository>
                <repository>
                  <id>redhat-ga</id>
                  <url>{{  $nexus.config.url }}/repository/redhat-ga/</url>
                </repository>
            </repositories>
            <pluginRepositories>
              <pluginRepository>
                  <id>public</id>
                  <url>{{ $nexus.config.url }}/repository/maven-public/</url>
              </pluginRepository>
            </pluginRepositories>
          </profile>    
      </profiles>
      <activeProfiles>
        <activeProfile>nexus</activeProfile>
      </activeProfiles>
    </settings>
{{ end }}
{{ end }}