{{ if .Values.pipelines }}
{{ range $pipeline := .Values.pipelines }}
{{ $pvcSize := $pipeline.pvcSize | default "2Gi"  }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-build-workspace-{{ $pipeline.pipelineName }}
  namespace: {{ $pipeline.namespace }}
spec:
  resources:
    requests:
      storage: {{$pipeline.pvcSize}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
{{ end }}
{{ end }}
