config:
  nexus: http://nexus.cicd.svc.cluster.local:8081
  nexusUser: admin
  nexusPass: admin123

pipelines: 
  - projectOcName: ms-boletoes-dev2
    
    type: javaSemSonar
    pipeName: ms-boleto-pipeline-dev
    appSourceGit: 'https://github.com/raycon300/app-service'
    appSourceBranch: 'main'
    appManifestGit: 'https://github.com/raycon300/app-service-gitops-dev'
    appManifestGitBranch: 'main'
    appManifestPath: 'oc-manifests'
    appImageUrl: latest
    appImageTag: latest
    gitHashCommit: '1.0.0'
