nexus:
  config:
    url: http://nexus.cicd.svc.cluster.local:8081
    user: admin
    pass: admin123

pipelines: 
  - namespace: ms-boletoes-dev3
    pipelineName: ms-boleto-pipeline-dev
    sourceRepository: 'https://github.com/raycon300/app-service'
    sourceBranch: 'main'
    sourceGitHashCommit: '1.0.0'
    gitOpsRepository: 'https://github.com/raycon300/app-service-gitops-dev'
    gitOpsBranch: 'main'
    gitOpsPath: 'oc-manifests'
    containerImage: latest
    containerImageTag: latest
    namespaceProd: ms-boletoes-prod
    pvcSize: 2Gi 

